version: "2.0"
services:
    common:
        volumes:
            - ./config:/config:ro
    chaijin:
        extends:
            service: common
        build:
            context: ./ChaiJin
        environment:
            - COMMON_CONFIG=/config/config.yaml
            - RPC=/config/ChaiJin/rpc.hjson
            - LOG=debug