version: '2.0'
services:
  mongo:
    image: mongo
    container_name: hyku.mongo.local
    volumes:
      - ./.data/mongo:/data
  mysql:
    image: mysql:5.7
    container_name: hyku.mysql.local
    volumes:
      - ./ChaiJin/doc/mysql:/docker-entrypoint-initdb.d:ro
#      - ./docs/dev/db:/docker-entrypoint-initdb.d:ro
      - ./.data/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=hyku_db
  redis:
    image: redis
    container_name: hyku.redis.local
  chaijin.internal.admin:
    extends:
      file: base.yml
      service: chaijin
    build:
      dockerfile: internal-admin.Dockerfile
    container_name: hyku.cj.admin
    links:
      - redis
      - mysql
    environment:
      - CONFIG=/config/internal-admin.yaml
  chaijin.external.console:
    extends:
      file: base.yml
      service: chaijin
    build:
      dockerfile: external-console.Dockerfile
    container_name: hyku.cj.console
    links:
      - chaijin.internal.admin
    environment:
      - CONFIG=/config/external-console.yaml
#  xiaorang:
#    build: ./XiaoRang
#    image: xiaorang
#    container_name: xr
#    links:
#      - redis
#    volumes:
#      - ./XiaoRang/src:/workspace/src:ro
#      - ./config/XiaoRang:/config:ro
  hyku.gateway.local:
    image: nginx
    container_name: hyku.gateway.local
    links:
      - chaijin.external.console
    volumes:
      - ./assets:/assets:ro
      - ./docker/nginx:/etc/nginx/conf.d:ro
    ports:
      - 80:80
  assets.build:
    build: ./assets
    image: assets.build
    container_name: assets
    volumes:
      - ./assets/:/env/console/assets/
      - ./assets/:/env/app/assets/
      - ./docs/:/docs/
    tty: true

