version: '2.0'
services:
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data
#    ports:
#      - 27017:27017
  redis:
    image: redis
  chaijin.external.app:
    build: ./docker/chaijin.external.app
    image: chaijin.external.app
    links:
      - mongo
      - redis
    volumes:
      - ./ChaiJin:/workspace:ro
      - ./config/ChaiJin:/config:ro
    extra_hosts:
      - service.self.internal.hyku.com:127.17.0.1
  chaijin.external.console:
    build: ./docker/chaijin.external.console
    image: chaijin.external.console
    volumes:
      - ./ChaiJin:/workspace:ro
      - ./config/ChaiJin:/config:ro
    extra_hosts:
      - service.self.internal.hyku.com:127.17.0.1
  chaijin.internal.admin:
    build: ./docker/chaijin.internal.admin
    image: chaijin.internal.admin
    links:
      - mongo
      - redis
    volumes:
      - ./ChaiJin:/workspace:ro
      - ./config/ChaiJin:/config:ro
    extra_hosts:
      - service.self.internal.hyku.com:127.17.0.1
  chaijin.internal.content:
    build: ./docker/chaijin.internal.content
    image: chaijin.internal.content
    links:
      - mongo
      - redis
    volumes:
      - ./ChaiJin:/workspace:ro
      - ./config/ChaiJin:/config:ro
    extra_hosts:
      - service.self.internal.hyku.com:127.17.0.1
  hyku.gateway:
#    build: ./docker/nginx
#    image: hyku.gateway
    image: nginx
    links:
      - chaijin.external.app
      - chaijin.external.console
      - chaijin.internal.admin
      - chaijin.internal.content
    volumes:
      - ./assets/:/assets:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
  assets.build:
    build: ./assets
    image: assets.build
    volumes:
      - ./assets/:/env/console/assets/
      - ./assets/:/env/app/assets/
    tty: true

