# Port to listen on, optional, default value is 80. This 
# configration item will be override by environment variable CONTENT_CONSOLE_PORT.
port: 80

# Secret key for cookie.
cookie_secret: hyku

log:
    # log level, 默认为INFO, 可选值为DEBUG|INFO|WARNING|ERROR, 等级依次增加
    level: DEBUG

static_files:
  CDN: http://cdn.cn.hyku.org
  RAW: http://cdn.cn.hyku.org


