# Port to listen on, optional, default value is 80. This 
# configration item will be override by environment variable CONTENT_CONSOLE_PORT.
port: 80

# Secret key for cookie.
cookie_secret: hyku

redis:
    host: redis
    port: 6379

#数据库配置，可配置多个
databases:
    #id: 由程序规定，程序内会以此来获取数据库的句柄
    #type: 数据库类型,sql或nosql
    #engine: 具体的数据库引擎，目前支持"mongodb"
    #host: 数据库主机的端口
    #port: 数据库服务的端口
    #username|password: 用户相关
    -   id: admin_db
        type: sql
        engine: mysql
        host: mysql
#        host: db-mysql.dev-cn.internal.hyku.org
        port: 3306
        user: root
        passwd: pabb
        db: dev_cn_db_console
